### ISSUE TITLE
Potential security issue in src/platform_w32_common/Timer.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/Bonzomatic#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/platform_w32_common/Timer.cpp` 
Function: `QueryPerformanceFrequency@4` 
https://github.com/sagpant/Bonzomatic/blob/0939b1ca6e7aee07512d5e2b7b9c7b757b33e490/src/platform_w32_common/Timer.cpp#L15
Code extract:

```cpp
      QueryPerformanceCounter(&LastPCV);
    }
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq); <------ HERE

    currentTime += (double)(count.QuadPart - LastPCV.QuadPart) / (double)(freq.QuadPart);
```

**How can I fix it?** 
Correct reference usage found in `external/glfw/src/win32_time.c` at line `41`.
https://github.com/sagpant/Bonzomatic/blob/0939b1ca6e7aee07512d5e2b7b9c7b757b33e490/external/glfw/src/win32_time.c#L41
Code extract:

```cpp
{
    uint64_t frequency;

    if (QueryPerformanceFrequency((LARGE_INTEGER*) &frequency)) <------ HERE
    {
        _glfw.timer.win32.hasPC = GLFW_TRUE;
```

**Comment by siva-msft** [comment]
this is a good find. Likely bug
